image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=repository"

cache:
  paths:
    - repository/
    - target/

build:
  stage: build
  script:
    - echo "Building project"
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - echo "Running test"
    - mvn $MAVEN_CLI_OPTS test
